name: Build SQLite for WASI

on:
  workflow_dispatch: # run manually
  push:
    tags:
      - "v*"

jobs:
  build-sqlite-wasi:
    runs-on: ubuntu-latest
    container: ghcr.io/webassembly/wasi-sdk:sha-d90d7de@sha256:ad430eedb6c51fecf657685d7ef538a9677cc937b47f2799ba14e6a487ad334b

    steps:
      - uses: actions/checkout@v4

      - name: Build sqlite3 for WASI
        run: |
          mkdir -p build/wasi
          clang --sysroot=/wasi-sdk-20/share/wasi-sysroot \
                --target=wasm32-wasip1 \
                -O2 -c vendor/sqlite/sqlite3.c -o build/wasi/sqlite3.o \
                -DSQLITE_CORE \
                -DSQLITE_THREADSAFE=0 \
                -DSQLITE_OMIT_LOAD_EXTENSION=1 \
                -DSQLITE_DEFAULT_FOREIGN_KEYS=1
          ar rcs build/wasi/libsqlite3.a build/wasi/sqlite3.o

      - name: Upload libsqlite3.a as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsqlite3-wasi
          path: build/wasi/libsqlite3.a
