name: Tests

on:
  [push]

env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color

jobs:

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
#          - os: ubuntu-latest
#            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add wasm32-wasip1

      - name: Download WASI-SDK and wasi2ic
        run: prepare.sh -y
          
      - name: Check clang install
        run: |
          echo `which clang`
          clang --version

      - name: Check WASI_SDK
        run: |
          echo WASI_SDK...
          echo $WASI_SDK
          echo ...

      - name: Build
        run: cargo build --release --target wasm32-wasip1
        
